export type Sensor = {
  id: number;
  measurementType: string;
  sensorName: string;
  unitSymbol: string;
};

export const SENSOR_NAMES = {
  PARTICULATE_MATTER: {
    AIRBEAM_PM25: "AirBeam-PM2.5",
    AIRBEAM_PM10: "AirBeam-PM10",
    AIRBEAM_PM1: "AirBeam-PM1",
    GOVERNMENT_PM25: "Government-PM2.5",
  },
  HUMIDITY: "AirBeam-RH",
  NITROGEN_DIOXIDE: "Government-NO2",
  OZONE: "Government-Ozone",
  TEMPERATURE: "AirBeam-F",
  SOUND_LEVEL: "Phone Microphone",
};

export const BasicSensorTypes = {
  HUMIDITY: SENSOR_NAMES.HUMIDITY,
  NITROGEN_DIOXIDE: SENSOR_NAMES.NITROGEN_DIOXIDE,
  OZONE: SENSOR_NAMES.OZONE,
  PARTICULATE_MATTER: {
    MOBILE: [
      SENSOR_NAMES.PARTICULATE_MATTER.AIRBEAM_PM25,
      SENSOR_NAMES.PARTICULATE_MATTER.AIRBEAM_PM10,
      SENSOR_NAMES.PARTICULATE_MATTER.AIRBEAM_PM1,
    ],
    FIXED: [
      SENSOR_NAMES.PARTICULATE_MATTER.AIRBEAM_PM25,
      SENSOR_NAMES.PARTICULATE_MATTER.AIRBEAM_PM10,
      SENSOR_NAMES.PARTICULATE_MATTER.AIRBEAM_PM1,
      SENSOR_NAMES.PARTICULATE_MATTER.GOVERNMENT_PM25,
    ],
  },
  SOUND_LEVEL: SENSOR_NAMES.SOUND_LEVEL,
  TEMPERATURE: SENSOR_NAMES.TEMPERATURE,
};
