common: &defaults
  host: localhost:3000
  mailer_from: noreply@localhost
  attachment_secret: "some long and random string"

test:
  <<: *defaults

development:
  <<: *defaults

staging:
  <<: *defaults
  host: aircasting.demo.llp.pl
  mailer_from: "AirCasting <noreply@aircasting.demo.llp.pl>"

production:
  <<: *defaults
  host: aircasting.org
  mailer_from: "AirCasting <noreply@aircasting.org>"
