import { jest } from "@jest/globals";

const mockFn = () => jest.fn();

export const createMockMapParams = () => ({
  currentUserSettings: "MapView",
  previousUserSettings: "MapView",
  sessionType: "fixed",
  isActive: true,
  isIndoor: false,
  currentCenter: { lat: 0, lng: 0 },
  currentZoom: 10,
  boundEast: 0,
  boundNorth: 0,
  boundSouth: 0,
  boundWest: 0,
  searchParams: new URLSearchParams(),
  goToUserSettings: mockFn(),
  revertUserSettingsAndResetIds: mockFn(),
  unitSymbol: "µg/m³",
  thresholdMin: "0",
  thresholdLow: "25",
  thresholdMiddle: "50",
  thresholdHigh: "75",
  thresholdMax: "100",
  initialThresholds: {
    min: 0,
    low: 25,
    middle: 50,
    high: 75,
    max: 100,
  },
  fetchedSessions: 0,
  updateLimit: mockFn(),
  updateOffset: mockFn(),
  mapTypeId: "roadmap",
  measurementType: "Particulate Matter",
  offset: 0,
  limit: 50,
  previousCenter: { lat: 0, lng: 0 },
  previousZoom: 10,
  sensorName: "PM2.5",
  sessionId: null,
  streamId: null,
  tags: "",
  timeFrom: "",
  timeTo: "",
  updateFetchedSessions: mockFn(),
  usernames: "",
});

export const MOCK_SESSION = {
  id: 1,
  title: "Test Session",
  sensorName: "PM2.5",
  averageValue: 10,
  startTime: "2023-01-01",
  endTime: "2023-01-02",
  streamId: 1,
};
